//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.8745
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace printurls.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("printurls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure to quit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreYouSureToQuit {
            get {
                return ResourceManager.GetString("AreYouSureToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete check has not finished in 10 seconds. Are you cancel Complete Check? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelCompleteCheck {
            get {
                return ResourceManager.GetString("CancelCompleteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval Wait:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INTERVAL_WAIT {
            get {
                return ResourceManager.GetString("INTERVAL_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Urls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOURL {
            get {
                return ResourceManager.GetString("NOURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAUSED {
            get {
                return ResourceManager.GetString("PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer is busy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRINTERISBUSY {
            get {
                return ResourceManager.GetString("PRINTERISBUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   printing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRINTING {
            get {
                return ResourceManager.GetString("PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entered URL includes &apos;[&apos; and &apos;]&apos;. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URL_INCLUDES_BLANCKET_CONTINUE {
            get {
                return ResourceManager.GetString("URL_INCLUDES_BLANCKET_CONTINUE", resourceCulture);
            }
        }
    }
}
